/* SPDX-License-Identifier: GPL-2.0 */
/* Generated by Documentation/scheduler/sched-pelt; do not modify. */

static const u32 runnable_avg_yN_inv[] __maybe_unused = {
	0xffffffff,0xeac0c6e6,0xd744fcc9,0xc5672a10,
	0xb504f333,0xa5fed6a9,0x9837f050,0x8b95c1e3,
};

static const u32 runnable_avg_yN_sum[] = {
	    0,  939, 1800, 2589, 3313, 3977, 4585, 5143, 5655,
};

#define LOAD_AVG_PERIOD 8
#define LOAD_AVG_MAX 12326
#define LOAD_AVG_MAX_N 85
